services:
  - type: web
    name: study-assistant-backend
    env: python
    region: ohio
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MONGO_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
